services:
  - type: web
    name: nutrisalud-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        value: nutrisalud-secret-key-2024-secure
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
